# Generated by Django 3.0.6 on 2020-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(unique=True)),
                ('linkName', models.TextField()),
                ('opis', models.TextField()),
                ('kategorie', models.TextField()),
            ],
        ),
    ]
